spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/?
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:config/log4j-local.xml
jwt:
  secret: axiaSecret
  user:
    accessToken:
      expirationInMinute: 30
    refreshToken:
      expirationInMinute: 720