spring:
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://vote.civiokbpzd6f.ap-northeast-2.rds.amazonaws.com/axia
      username: axia
      password: shfkdxhdekfr12#$
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:config/log4j-local.xml
jwt:
  secret: axiaSecret
  user:
    accessToken:
      expirationInMinute: 30
    refreshToken:
      expirationInMinute: 720
