spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: http://localhost:3306
      username: root
      password: root
logging:
  config: classpath:config/log4j-local.xml
jwt:
  secret: axiaSecret
  user:
    accessToken:
      expirationInMinute: 30
    refreshToken:
      expirationInMinute: 720